// Generated by Wrangler by running `wrangler types`

export interface Env {
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_TOKEN: string;
	DISCORD_TEST_GUILD_ID: string;
	DB: D1Database;
}
